# Generated by Django 3.2.5 on 2021-08-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20210830_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Github',
            new_name='github',
        ),
    ]
